language: node_js
node_js:
  - "4.1"
services:
  - postgresql
install:
  - npm install
before_script:
  - npm run lint
  - cp server/config/config.json.travis server/config/config.json
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm run sequalize -- db:migrate
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - npm run build
  - npm test
