language: node_js
node_js:
  - "4.2.6"
addons:
  postgresql: "9.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - postgresql
env:
  - NODE_ENV=test
  global:
    - CXX=g++-4.8
before_install:
  - cp server/config/secrets.json.example server/config/secrets.json
  - cp server/config/config.json.travis server/config/config.json
  - mkdir -p server/log
  - psql -c 'create database travis_ci_test;' -U postgres
install:
  - npm install
before_script:
  - npm run lint
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - npm run build
  - npm test
